import ThemeProvider from '@/components/theme-provider';
import type { Metadata } from 'next';
import localFont from 'next/font/local';

import './globals.css';

const pretendardFont = localFont({
  src: '../public/fonts/PretendardVariable.woff2',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={pretendardFont.className}>
        <ThemeProvider
          attribute="class"
          // NOTE - 기본적으로 다크모드로 설정하였습니다.
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
